### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by zettysource**

### CODE REVIEW

**Comment by mtigas** [comment]
Hi, this looks to be the default example GitHub Workers `main.yml` file. It does not actually appear to do any building or testing.

You're free to tinker with doing continuous integration bits in a fork, but this is not a valid pull request as it neither adds functionality nor does it even contain a "work in progress" to do so. We're happy to look at pull requests and code edits once they represent code that is in working condition, or at least represent a good amount of effort toward working condition.

**Comment by zettysource** [comment]
Can plz help get the app. Dont get how

**Comment by mtigas** [comment]
Onion Browser is available on the App Store here:  
https://apps.apple.com/us/app/onion-browser/id519296448

If you are unable to install the app from the App Store, the only other way to do so is by compiling the app yourself with Apple's developer tools (Xcode); however, we can't provide technical support or assistance for this.

**Comment by zettysource** [comment]
I got iPhone what's way I can access tor and Dark web on iPhone plz would help would be appreciated

**Pull request closed without merging**
